// ============================================================================
// Telegram Channel Configuration — ported from SKILL.md (235 unique channels)
// ============================================================================

export interface ChannelConfig {
  username: string;
  label: string;
  category: string;
  language: string;
  trustTier: "core" | "verified" | "watch";
  latencyTier: "instant" | "fast" | "monitor";
  sourceType: "official" | "milblog" | "osint" | "analysis" | "journalism";
  acquisitionMethod: "telegram_public";
  domainTags: string[];
  subscriberValueScore: number;
}

export const CATEGORIES: Record<string, string> = {
  ua_official: "Ukrainian Official",
  ua_osint: "Ukrainian OSINT",
  ua_intel: "Ukrainian Intelligence",
  ua_frontline: "Ukrainian Frontline Units",
  ua_journalism: "Ukrainian Journalism",
  ru_official: "Russian Official",
  ru_milblog: "Russian Milbloggers",
  en_analysis: "English Analysis",
  en_osint: "English OSINT",
  israel_milblog: "Israel / Mideast Intel",
  iran_milblog: "Iran / Resistance Axis",
  syria_osint: "Syria & Levant",
  global_osint: "Global OSINT",
  weapons: "Weapons & Equipment",
  mapping: "Mapping & Geolocation",
  cyber: "Cyber Warfare",
  naval: "Naval / Maritime",
  air_defense: "Air Defense & Monitoring",
  casualties: "Casualties & Equipment Losses",
  satellite: "Satellite & Geospatial OSINT",
  weibo_satellite: "Weibo Satellite Intel",
  drone: "Drone Warfare",
  foreign_vol: "Foreign Volunteer Units",
  think_tank: "Think Tanks & Analysis",
  middle_east_osint: "Middle East OSINT",
  sudan_conflict: "Sudan & East Africa",
  africa_osint: "Africa OSINT",
  asia_pacific_osint: "Asia-Pacific OSINT",
  south_asia_osint: "South Asia Conflict",
  nato_tracking: "NATO Tracking",
  nuclear_monitoring: "Nuclear Monitoring",
  latam_security: "Latin America Security",
  cartel_osint: "Cartel & Narco OSINT",
  south_america_osint: "South America Security",
};

const CATEGORY_LANG: Record<string, string> = {
  ua_official: "uk",
  ua_osint: "uk",
  ua_intel: "uk",
  ua_frontline: "uk",
  ua_journalism: "uk",
  ru_official: "ru",
  ru_milblog: "ru",
  israel_milblog: "he",
  iran_milblog: "fa",
  syria_osint: "ar",
  weibo_satellite: "zh",
  asia_pacific_osint: "zh",
  latam_security: "es",
  cartel_osint: "es",
  south_america_osint: "es",
};

const CATEGORY_DOMAIN_TAGS: Record<string, string[]> = {
  ua_official: ["conflict", "official", "ukraine"],
  ua_osint: ["conflict", "osint", "ukraine"],
  ua_intel: ["conflict", "intel", "ukraine"],
  ua_frontline: ["conflict", "frontline", "ukraine"],
  ua_journalism: ["conflict", "journalism", "ukraine"],
  ru_official: ["conflict", "official", "russia"],
  ru_milblog: ["conflict", "milblog", "russia"],
  en_analysis: ["analysis", "global"],
  en_osint: ["osint", "global"],
  israel_milblog: ["conflict", "middle-east", "milblog"],
  iran_milblog: ["conflict", "middle-east", "milblog"],
  syria_osint: ["conflict", "middle-east", "osint"],
  global_osint: ["osint", "global"],
  weapons: ["military", "equipment", "osint"],
  mapping: ["mapping", "geolocation", "osint"],
  cyber: ["osint_cyber", "cyber", "security"],
  naval: ["naval", "maritime", "military"],
  air_defense: ["air", "air-defense", "military"],
  casualties: ["casualties", "equipment-losses", "osint"],
  satellite: ["satellite", "geospatial", "osint"],
  weibo_satellite: ["satellite", "geospatial", "east-asia"],
  drone: ["drone", "military", "osint"],
  foreign_vol: ["military", "personnel", "ukraine"],
  think_tank: ["analysis", "policy", "think-tank"],
  middle_east_osint: ["middle-east", "osint"],
  sudan_conflict: ["africa", "conflict", "osint"],
  africa_osint: ["africa", "osint"],
  asia_pacific_osint: ["asia-pacific", "osint"],
  south_asia_osint: ["south-asia", "osint"],
  nato_tracking: ["nato", "military", "tracking"],
  nuclear_monitoring: ["nuclear", "strategic", "monitoring"],
  latam_security: ["latam", "security", "osint"],
  cartel_osint: ["latam", "cartel", "osint"],
  south_america_osint: ["south-america", "security", "osint"],
};

const CATEGORY_SOURCE_TYPE: Record<string, ChannelConfig["sourceType"]> = {
  ua_official: "official",
  ru_official: "official",
  think_tank: "analysis",
  en_analysis: "analysis",
  ua_journalism: "journalism",
  cyber: "osint",
  global_osint: "osint",
  en_osint: "osint",
  mapping: "osint",
  satellite: "osint",
  weibo_satellite: "osint",
  nato_tracking: "official",
  nuclear_monitoring: "analysis",
  latam_security: "journalism",
  cartel_osint: "osint",
};

const CATEGORY_TRUST_TIER: Record<string, ChannelConfig["trustTier"]> = {
  ua_official: "core",
  ru_official: "verified",
  think_tank: "verified",
  en_analysis: "verified",
  ua_journalism: "verified",
  nato_tracking: "verified",
  nuclear_monitoring: "verified",
  cyber: "verified",
};

const CATEGORY_LATENCY_TIER: Record<string, ChannelConfig["latencyTier"]> = {
  ua_official: "instant",
  ua_frontline: "instant",
  ru_official: "fast",
  ru_milblog: "instant",
  israel_milblog: "instant",
  iran_milblog: "instant",
  global_osint: "instant",
  en_osint: "fast",
  cyber: "fast",
  air_defense: "instant",
  drone: "instant",
  naval: "fast",
};

const CATEGORY_SUBSCRIBER_VALUE: Record<string, number> = {
  ua_official: 96,
  ua_frontline: 95,
  ua_intel: 95,
  ru_milblog: 92,
  ru_official: 88,
  israel_milblog: 90,
  iran_milblog: 89,
  global_osint: 87,
  en_osint: 86,
  cyber: 88,
  air_defense: 90,
  satellite: 88,
  drone: 89,
  naval: 84,
  think_tank: 74,
};

// [username, label, category]
const RAW: Array<[string, string, string]> = [
  // --- Ukrainian Official ---
  ["ukraine_context", "Ukraine Context", "ua_official"],
  ["GeneralStaffZSU", "UA General Staff", "ua_official"],
  ["UkrainianLandForces", "UA Ground Forces", "ua_official"],
  ["ukaborona", "UA Ministry of Defense", "ua_official"],
  ["AFUStratCom", "AFU Strategic Comms", "ua_official"],
  ["air_alert_ua", "UA Air Alerts", "ua_official"],
  ["kpszsu", "UA Air Force Command", "ua_official"],
  // --- Ukrainian OSINT ---
  ["DeepStateUA", "DeepState Map", "ua_osint"],
  ["operativnoZSU", "Operatyvnyi ZSU", "ua_osint"],
  ["Kherson_molodec", "Kherson Insider", "ua_osint"],
  ["supernova_plus", "Supernova+", "ua_osint"],
  ["pilotblog", "Denys Davydov", "ua_osint"],
  ["OSINT_Ukraine_Aggregation", "UA OSINT Aggregator", "ua_osint"],
  ["oper_ZSU", "Operator ZSU", "ua_osint"],
  // --- Ukrainian Intelligence ---
  ["SBUkr", "SBU Security Service", "ua_intel"],
  ["informnapalm", "InformNapalm OSINT", "ua_intel"],
  ["DIUkraine", "GUR Defense Intelligence", "ua_intel"],
  ["Atesh_UA", "ATESH Partisan Movement", "ua_intel"],
  ["Molfar_global", "Molfar OSINT", "ua_intel"],
  // --- Ukrainian Frontline Units ---
  ["azov_media", "Azov Brigade", "ua_frontline"],
  ["kraken_kha", "Kraken Unit Kharkiv", "ua_frontline"],
  ["Soniashnyk", "Soniashnyk Aviation", "ua_frontline"],
  ["ua3brigade", "3rd Assault Brigade", "ua_frontline"],
  ["mechanized47", "47th Mech Brigade", "ua_frontline"],
  ["marines_36", "36th Marine Infantry", "ua_frontline"],
  ["zsu35obmp", "35th Marine Brigade", "ua_frontline"],
  ["UKRAINE8841", "88th Separate Mech Brigade", "ua_frontline"],
  // --- Ukrainian Journalism ---
  ["ssternenko", "Sternenko", "ua_journalism"],
  ["ButusovPlus", "Butusov Plus", "ua_journalism"],
  ["ivan_fedorov_zp", "Zaporizhzhia RMA", "ua_journalism"],
  ["Tsaplienko", "Tsaplienko War Reporter", "ua_journalism"],
  ["pravda_gerashchenko", "Gerashchenko Advisor", "ua_journalism"],
  ["nikolaev_vanek", "Nikolayevsky Vanyok", "ua_journalism"],
  ["unaboronaua", "UNIAN War", "ua_journalism"],
  ["guildhall_org", "Guildhall", "ua_journalism"],
  ["vitaly_kim_mykolaiv", "Vitaly Kim", "ua_journalism"],
  ["Telegraf_Ukraine", "Telegraf Ukraine", "ua_journalism"],
  // --- Russian Official ---
  ["mod_russia", "Russian MOD", "ru_official"],
  ["mod_russia_en", "Russian MOD (English)", "ru_official"],
  ["MID_Russia", "Russian MFA", "ru_official"],
  ["MFARussia", "Russian MFA (English)", "ru_official"],
  ["saldo_vga", "Vladimir Saldo (Kherson)", "ru_official"],
  ["tass_agency", "TASS", "ru_official"],
  ["rian_ru", "RIA Novosti", "ru_official"],
  // --- Russian Milbloggers ---
  ["rybar", "Rybar", "ru_milblog"],
  ["dva_majors", "Two Majors", "ru_milblog"],
  ["RVvoenkor", "RV Voenkor", "ru_milblog"],
  ["wargonzo", "WarGonzo", "ru_milblog"],
  ["strelkovii", "Strelkov / Girkin", "ru_milblog"],
  ["voenkorKotenok", "Voenkor Kotenok", "ru_milblog"],
  ["epoddubny", "Poddubny", "ru_milblog"],
  ["Sladkov_plus", "Sladkov+", "ru_milblog"],
  ["boris_rozhin", "Colonelcassad", "ru_milblog"],
  ["readovkanews", "Readovka", "ru_milblog"],
  ["voenacher", "Turned on War", "ru_milblog"],
  ["RKadyrov_95", "Kadyrov", "ru_milblog"],
  ["bomber_fighter", "Fighterbomber", "ru_milblog"],
  ["grey_zone", "Grey Zone / Wagner", "ru_milblog"],
  ["Starshe_eddy", "Starshe Eddy", "ru_milblog"],
  ["sudoplatov_official", "Sudoplatov Unit", "ru_milblog"],
  ["ASTRApress", "ASTRA Independent", "ru_milblog"],
  ["CITeam", "Conflict Intel Team", "ru_milblog"],
  ["milinfolive", "MilInfoLive", "ru_milblog"],
  ["RWApodcast", "Russians With Attitude", "ru_milblog"],
  ["milhelipilot", "Helicopter Pilot", "ru_milblog"],
  ["ConflictChronicles", "Chronicles of Conflict", "ru_milblog"],
  ["Russian_OSINT", "Russian OSINT", "ru_milblog"],
  ["intelslava", "Intel Slava Z", "ru_milblog"],
  ["SosijPriobin", "Military Observer", "ru_milblog"],
  ["aleksandr_kots", "Alexander Kots", "ru_milblog"],
  ["rlz_the_kraken", "Kraken Z", "ru_milblog"],
  ["medvedev_telegram", "Medvedev", "ru_milblog"],
  ["adelimkhanov_95", "Adelimkhanov", "ru_milblog"],
  ["osirskiy", "Osirskiy", "ru_milblog"],
  ["neoficialniybezsonov", "Unofficial Bezsonov", "ru_milblog"],
  ["sashakots", "Kotsnews", "ru_milblog"],
  ["voin_dv", "Voin DV", "ru_milblog"],
  ["opersvodki", "Operative Summaries", "ru_milblog"],
  ["mig41", "MIG Russia", "ru_milblog"],
  ["warfakes", "War on Fakes", "ru_milblog"],
  ["infantmilitario", "Militarist", "ru_milblog"],
  ["aptialaudinovakhmat", "Apti Alaudinov (Akhmat)", "ru_milblog"],
  ["russ_orientalist", "Russ Orientialist", "ru_milblog"],
  ["abbasdjuma", "Abbas Djuma", "ru_milblog"],
  ["zhivoff", "ZHIVOV", "ru_milblog"],
  ["zvezdanews", "Zvezda News", "ru_milblog"],
  ["anna_news", "ANNA News", "ru_milblog"],
  ["warhronika", "War Chronicle", "ru_milblog"],
  ["new_militarycolumnist", "Military Columnist", "ru_milblog"],
  // --- English Analysis ---
  ["NOELreports", "NOEL Reports", "en_analysis"],
  ["wartranslated", "War Translated", "en_analysis"],
  ["ukraine_front_lines", "Ukraine Front Lines", "en_analysis"],
  ["ISW_official", "Inst. for Study of War", "en_analysis"],
  ["UkraineNowEnglish", "Ukraine NOW English", "en_analysis"],
  ["militarysummary", "Military Summary", "en_analysis"],
  ["CITeam_en", "Conflict Intel Team EN", "en_analysis"],
  // --- English OSINT ---
  ["andrewperpetua", "Andrew Perpetua", "en_osint"],
  ["defmon3war", "DefMon3", "en_osint"],
  ["OsintUpdates", "OSINT Updates", "en_osint"],
  ["CalibreObscura", "Calibre Obscura", "en_osint"],
  ["MilitaryLand_net", "MilitaryLand.net", "en_osint"],
  ["IntelCrab", "Intel Crab", "en_osint"],
  // --- Israel / Mideast Intel ---
  ["AbuAliExpress", "Abu Ali Express (EN)", "israel_milblog"],
  ["AbuAliExpressHeb", "Abu Ali Express (HE)", "israel_milblog"],
  ["israelwarlive", "Israel War Live", "israel_milblog"],
  ["idlofficialchannel", "IDF Official", "israel_milblog"],
  ["ilofficialchannel", "IDF Telegram", "israel_milblog"],
  ["idfonline", "IDF Know What's Going On", "israel_milblog"],
  ["israelrealtimee", "Israel Realtime", "israel_milblog"],
  ["osikimovilim", "OSINT Israel & ME", "israel_milblog"],
  ["INTELMEONLINE", "Intel Middle East Online", "israel_milblog"],
  ["manikimovilim", "Manikimovilim", "israel_milblog"],
  ["kann_news", "Kann News", "israel_milblog"],
  ["N12News", "Channel 12 News", "israel_milblog"],
  ["Israel_Radar_EN", "Israel Radar English", "israel_milblog"],
  // --- Iran / Resistance Axis ---
  ["resistance_trench", "Resistance Trench", "iran_milblog"],
  ["CIG_telegram", "CIG Telegram", "iran_milblog"],
  ["RNN_English", "Resistance News Network", "iran_milblog"],
  ["hezbollah_ops", "Hezbollah Operations Room", "iran_milblog"],
  ["nujaba_media", "Nujaba Military Media", "iran_milblog"],
  ["yemen_press", "Yemen Press Agency", "iran_milblog"],
  ["ansarollah_en", "Ansarollah English", "iran_milblog"],
  ["sepahcybery", "IRGC Cyber Force", "iran_milblog"],
  ["Irna_en", "IRNA English", "iran_milblog"],
  ["tasnimnews", "Tasnim News", "iran_milblog"],
  ["farsna", "Fars News", "iran_milblog"],
  ["irna_ru", "IRNA Russian", "iran_milblog"],
  ["sabrennewss", "Sabereen News", "iran_milblog"],
  // --- Syria & Levant ---
  ["military_media_sy", "Military Media Syria", "syria_osint"],
  ["Suriyakmaps", "Suriyak Maps", "syria_osint"],
  ["KurdishFrontNews", "Kurdish Front News", "syria_osint"],
  ["YPGInfo", "YPG Press Office", "syria_osint"],
  ["YPJMediaCenter", "YPJ Media Center", "syria_osint"],
  ["Levant24", "Levant 24 Syria", "syria_osint"],
  // --- Global OSINT ---
  ["OSINTdefender", "OSINT Defender", "global_osint"],
  ["warmonitors", "War Monitor", "global_osint"],
  ["ourwarstoday", "Our Wars Today", "global_osint"],
  ["conflictstracker", "Conflicts Tracker", "global_osint"],
  ["conflictarchive", "Conflict Archive", "global_osint"],
  ["bellingcat", "Bellingcat", "global_osint"],
  ["bellingcatmonitoring", "Bellingcat Monitoring", "global_osint"],
  ["rnintel", "Rerum Novarum Intel", "global_osint"],
  ["drmjournal", "De Re Militari", "global_osint"],
  ["LiveuaMap", "LiveUA Map", "global_osint"],
  ["DefenderDome", "The Defender Dome", "global_osint"],
  ["OsintTv", "OSINT TV", "global_osint"],
  ["ClashReport", "Clash Report", "global_osint"],
  ["SudanWarMonitor", "Sudan War Monitor", "global_osint"],
  // --- Weapons & Equipment ---
  ["UAWeapons", "UA Weapons Tracker", "weapons"],
  ["UkraineWeaponsTracker", "Weapons Tracker (Oryx)", "weapons"],
  ["LostArmour", "Lost Armour Vehicle Tracker", "weapons"],
  // MilitaryLand_net already in en_osint — skipped
  // --- Mapping & Geolocation ---
  ["AMK_Mapping", "AMK Mapping", "mapping"],
  ["mapsukraine", "Ukraine Maps", "mapping"],
  ["war_mapper", "War Mapper", "mapping"],
  // --- Cyber Warfare ---
  ["itarmyofukraine2022", "IT Army of Ukraine", "cyber"],
  ["cyberknow20", "CyberKnow Threat Intel", "cyber"],
  ["CyberWarzone", "Cyber Warzone", "cyber"],
  ["vxunderground", "vx-underground", "cyber"],
  ["MalwareHunterTeam", "MalwareHunterTeam", "cyber"],
  ["DailyDarkWeb", "Daily Dark Web", "cyber"],
  ["gbhackers_news", "GBHackers News", "cyber"],
  ["TheDFIRReport", "The DFIR Report", "cyber"],
  ["RecordedFutureNews", "Recorded Future News", "cyber"],
  ["CiscoTalosIntelligence", "Cisco Talos Intelligence", "cyber"],
  ["MandiantAdvantage", "Mandiant Intelligence", "cyber"],
  ["SentinelLabs", "SentinelLabs", "cyber"],
  ["BleepingComputer", "BleepingComputer", "cyber"],
  ["CISAKevWatch", "CISA KEV Watch", "cyber"],
  ["CERT_EU_Security", "CERT-EU Security", "cyber"],
  ["SANSInternetStormCenter", "SANS ISC", "cyber"],
  ["OTXAlienVault", "AlienVault OTX", "cyber"],
  ["MISPProject", "MISP Project", "cyber"],
  ["ProjectZeroBlog", "Project Zero", "cyber"],
  ["HuntressLabs", "Huntress Labs", "cyber"],
  ["RedDrip7", "RedDrip7", "cyber"],
  ["Unit42_Intel", "Unit 42 Intel", "cyber"],
  ["Shadowserver", "Shadowserver", "cyber"],
  ["CVE_Threat_Intel", "CVE Threat Intel", "cyber"],
  // --- Naval / Maritime ---
  ["blackseastrategyinstitute", "Black Sea Strategy Inst.", "naval"],
  ["naval_intelligence", "Naval Intelligence", "naval"],
  ["WarshipCam", "Warship Cam", "naval"],
  // --- Air Defense & Monitoring ---
  ["warinukraineua", "Ukrainian Witness", "air_defense"],
  ["CyberspecNews", "CYBERSPEC Air/UAV", "air_defense"],
  ["MissileMap", "Missile Map", "air_defense"],
  // --- Casualties & Equipment Losses ---
  ["rf200_now_world", "Cargo-200 Casualties", "casualties"],
  // LostArmour already in weapons — skipped
  // --- Satellite & Geospatial OSINT ---
  ["sitreports", "SITREP OSINT", "satellite"],
  ["kalibrated", "Kalibrated Analysis", "satellite"],
  ["GeoSight", "The GeoSight", "satellite"],
  ["mercsat", "MERC-SAT Analytics", "satellite"],
  ["MenchOsint", "MenchOsint SATINT", "satellite"],
  // --- Weibo Satellite Intel ---
  ["weibo_6477763414", "MizarVision", "weibo_satellite"],
  // --- Drone Warfare ---
  ["aerorozvidka", "Aerorozvidka Drones", "drone"],
  ["fpv_drone_war", "FPV Drone Warfare", "drone"],
  ["dronesquad_ua", "Drone Squad UA", "drone"],
  // --- Foreign Volunteer Units ---
  ["georgian_legion", "Georgian Legion", "foreign_vol"],
  ["InternationalLegionUA", "International Legion UA", "foreign_vol"],
  ["fightforua", "Fight for UA", "foreign_vol"],
  // --- Think Tanks & Analysis ---
  ["noel_reports", "NOEL Reports Analysis", "think_tank"],
  ["RUSI_org", "RUSI Defence Think Tank", "think_tank"],
  ["IISS_org", "IISS Strategic Studies", "think_tank"],
  // --- Middle East OSINT ---
  ["beholdisraelchannel", "Behold Israel", "middle_east_osint"],
  ["Yemenimilitary", "Yemen Military", "middle_east_osint"],
  ["OSESGY1", "UN Envoy Yemen", "middle_east_osint"],
  ["yemenmofa", "Yemen MFA (Sanaa)", "middle_east_osint"],
  ["BasedIMINT", "Based IMINT", "middle_east_osint"],
  // --- Sudan & East Africa ---
  ["RSFSudan", "RSF Sudan", "sudan_conflict"],
  ["GeneralDagalo", "Hemedti / RSF Commander", "sudan_conflict"],
  ["newsfromsudan", "News from Sudan", "sudan_conflict"],
  ["SudanNewsEnglish", "Sudan News Network", "sudan_conflict"],
  ["Channel29News", "Ethiopia / Tigray Conflict", "sudan_conflict"],
  ["tsegaye_r_ararsaa", "OLA Oromo Liberation", "sudan_conflict"],
  ["borkena", "Borkena Ethiopia", "sudan_conflict"],
  // --- Africa OSINT ---
  ["AlmanaraMedia", "Libya LNA / Haftar Media", "africa_osint"],
  ["xlrmedia", "Africa News Aggregator", "africa_osint"],
  ["addis_news", "Addis News", "africa_osint"],
  ["gebeyanews", "Gebeya News", "africa_osint"],
  // --- Asia-Pacific OSINT ---
  ["chinamilitary", "China Military", "asia_pacific_osint"],
  ["SouthChinaSea", "South China Sea", "asia_pacific_osint"],
  ["taiwannews", "Taiwan News", "asia_pacific_osint"],
  ["ETReport", "Korea / DPRK Monitor", "asia_pacific_osint"],
  ["xinhua_news_agency_en", "Xinhua News EN", "asia_pacific_osint"],
  ["xinhua_news_agency_ru", "Xinhua News RU", "asia_pacific_osint"],
  // --- South Asia Conflict ---
  ["thekashmirgraph", "Kashmir News Portal", "south_asia_osint"],
  ["DSquadOfficial", "Defence Squad Pak-India", "south_asia_osint"],
  ["meghupdates", "India Security Updates", "south_asia_osint"],
  // --- NATO Tracking ---
  ["nato_aircom", "NATO Air Command", "nato_tracking"],
  ["natoarmynews", "NATO Army News", "nato_tracking"],
  ["natovideos", "NATO Videos", "nato_tracking"],
  // --- Nuclear Monitoring ---
  ["defcon_alerts", "Defcon Alerts", "nuclear_monitoring"],
  ["DEFCONWarningSystem", "DEFCON Warning System", "nuclear_monitoring"],
  // --- Latin America Security ---
  ["InsightCrimeEN", "InSight Crime", "latam_security"],
  ["BorderlandBeat", "Borderland Beat", "latam_security"],
  ["ColombiaReports", "Colombia Reports", "latam_security"],
  ["VenezuelaIntl", "Venezuela Intl", "latam_security"],
  ["HaitiInfoProject", "Haiti Info Project", "latam_security"],
  ["entre_guerras", "Entre Guerras", "latam_security"],
  ["Conflictos_Ecuador", "Ecuador Conflicts", "latam_security"],
  ["la_patilla", "La Patilla Venezuela", "latam_security"],
  ["sinembargomx", "SinEmbargo Mexico", "latam_security"],
  // --- Cartel & Narco OSINT ---
  ["MexicoViolencia", "Mexico Violencia", "cartel_osint"],
  ["NarcoFiles", "Narco Files", "cartel_osint"],
  ["CartelChronicles", "Cartel Chronicles", "cartel_osint"],
  ["warinmex", "War in Mexico", "cartel_osint"],
  ["NoticiasdelNarco", "Blog del Narco", "cartel_osint"],
  ["elblogdelnarcoofc", "Blog del Narco (Official)", "cartel_osint"],
  ["thecartelchannel", "The Cartel Channel", "cartel_osint"],
  ["carteldelmexico_off", "Cartel de Mexico", "cartel_osint"],
  ["alertachiapas", "Alerta Chiapas", "cartel_osint"],
  ["ElGuero_Mx", "El Guero Mexico", "cartel_osint"],
  ["MUNDONARCOMX", "Mundo Narco MX", "cartel_osint"],
  // --- South America Security ---
  ["intervencionpolicia", "Peru Police Operations", "south_america_osint"],
  ["quepasaaraucania", "Araucania/Mapuche Conflict", "south_america_osint"],
  ["frentemilitargeo", "LATAM Military & Geopolitics", "south_america_osint"],
  ["Movimiento_Disidente", "LATAM Dissident Movements", "south_america_osint"],
  ["correodelsur", "Correo del Sur Bolivia", "south_america_osint"],
  ["AvispaMidia", "Amazon Indigenous Conflict", "south_america_osint"],
];

// Deduplicate by username (first occurrence wins)
const seen = new Set<string>();
export const CHANNELS: ChannelConfig[] = [];
for (const [username, label, category] of RAW) {
  if (seen.has(username)) continue;
  seen.add(username);
  CHANNELS.push({
    username,
    label,
    category,
    language: CATEGORY_LANG[category] || "en",
    trustTier: CATEGORY_TRUST_TIER[category] || "watch",
    latencyTier: CATEGORY_LATENCY_TIER[category] || "monitor",
    sourceType: CATEGORY_SOURCE_TYPE[category] || (category.includes("official") ? "official" : category.includes("milblog") ? "milblog" : category.includes("journalism") ? "journalism" : category.includes("analysis") || category.includes("think_tank") ? "analysis" : "osint"),
    acquisitionMethod: "telegram_public",
    domainTags: CATEGORY_DOMAIN_TAGS[category] || ["osint"],
    subscriberValueScore: CATEGORY_SUBSCRIBER_VALUE[category] || 72,
  });
}
