export type OsintAcquisitionMethod =
  | "rss"
  | "api"
  | "dataset"
  | "scrape"
  | "social_monitor"
  | "telegram_public";

export type OsintTrustTier = "core" | "verified" | "watch";
export type OsintLatencyTier = "instant" | "fast" | "monitor";
export type OsintSourceType =
  | "official"
  | "wire"
  | "newsroom"
  | "analysis"
  | "osint"
  | "dataset"
  | "social";

export type OsintSource = {
  id: string;
  name: string;
  category: "newsroom" | "osint_collective" | "conflict_tracker" | "regional_analyst" | "humanitarian";
  description: string;
  url: string;
  feedUrl?: string;
  region: string;
  language: string;
  reliability: "high" | "medium";
  tags: string[];
  acquisitionMethod: OsintAcquisitionMethod;
  trustTier: OsintTrustTier;
  latencyTier: OsintLatencyTier;
  sourceType: OsintSourceType;
  mediaCapability: Array<"text" | "image" | "video" | "map" | "document" | "dataset">;
  scrapeRisk: "low" | "medium" | "high";
  subscriberValueScore: number;
};

type BaseOsintSource = Omit<
  OsintSource,
  "acquisitionMethod" | "trustTier" | "latencyTier" | "sourceType" | "mediaCapability" | "scrapeRisk" | "subscriberValueScore"
> &
  Partial<
    Pick<
      OsintSource,
      "acquisitionMethod" | "trustTier" | "latencyTier" | "sourceType" | "mediaCapability" | "scrapeRisk" | "subscriberValueScore"
    >
  >;

function inferSourceType(source: BaseOsintSource): OsintSourceType {
  if (source.tags.includes("dataset")) return "dataset";
  if (source.tags.includes("wire")) return "wire";
  if (source.tags.includes("social") || source.tags.includes("reddit") || source.tags.includes("bluesky") || source.tags.includes("youtube")) {
    return "social";
  }
  if (source.category === "osint_collective") return "osint";
  if (source.category === "regional_analyst") return "analysis";
  if (source.category === "newsroom") return "newsroom";
  return "official";
}

function inferAcquisitionMethod(source: BaseOsintSource): OsintAcquisitionMethod {
  if (source.feedUrl) return "rss";
  if (source.tags.includes("api")) return "api";
  if (source.tags.includes("dataset")) return "dataset";
  if (source.tags.includes("social") || source.tags.includes("reddit") || source.tags.includes("bluesky") || source.tags.includes("youtube")) {
    return "social_monitor";
  }
  return "scrape";
}

function inferTrustTier(source: BaseOsintSource): OsintTrustTier {
  if (source.reliability === "high" && (source.tags.includes("official") || source.tags.includes("wire") || source.tags.includes("dataset"))) {
    return "core";
  }
  return source.reliability === "high" ? "verified" : "watch";
}

function inferLatencyTier(source: BaseOsintSource): OsintLatencyTier {
  if (source.tags.includes("breaking") || source.tags.includes("alerts") || source.tags.includes("wire")) return "instant";
  if (source.feedUrl || source.tags.includes("api") || source.tags.includes("dataset")) return "fast";
  return "monitor";
}

function inferMediaCapability(source: BaseOsintSource): OsintSource["mediaCapability"] {
  const capabilities = new Set<OsintSource["mediaCapability"][number]>(["text"]);
  if (source.tags.includes("map")) capabilities.add("map");
  if (source.tags.includes("video") || source.tags.includes("youtube")) capabilities.add("video");
  if (source.tags.includes("image") || source.tags.includes("satellite") || source.tags.includes("visual-verification")) capabilities.add("image");
  if (source.tags.includes("document") || source.tags.includes("advisory") || source.tags.includes("sitreps")) capabilities.add("document");
  if (source.tags.includes("dataset") || source.tags.includes("api") || source.tags.includes("ads-b") || source.tags.includes("ais")) capabilities.add("dataset");
  return Array.from(capabilities);
}

function inferScrapeRisk(source: BaseOsintSource): OsintSource["scrapeRisk"] {
  if (source.feedUrl || source.tags.includes("api") || source.tags.includes("dataset")) return "low";
  if (source.tags.includes("social") || source.tags.includes("x-monitor")) return "high";
  return "medium";
}

function inferSubscriberValueScore(source: BaseOsintSource): number {
  let score = source.reliability === "high" ? 82 : 68;
  if (source.tags.includes("breaking")) score += 8;
  if (source.tags.includes("alerts")) score += 6;
  if (source.tags.includes("cyber")) score += 6;
  if (source.tags.includes("satellite") || source.tags.includes("ads-b") || source.tags.includes("ais")) score += 5;
  if (source.tags.includes("official") || source.tags.includes("wire")) score += 4;
  return Math.min(100, score);
}

function buildSource(source: BaseOsintSource): OsintSource {
  return {
    ...source,
    acquisitionMethod: source.acquisitionMethod ?? inferAcquisitionMethod(source),
    trustTier: source.trustTier ?? inferTrustTier(source),
    latencyTier: source.latencyTier ?? inferLatencyTier(source),
    sourceType: source.sourceType ?? inferSourceType(source),
    mediaCapability: source.mediaCapability ?? inferMediaCapability(source),
    scrapeRisk: source.scrapeRisk ?? inferScrapeRisk(source),
    subscriberValueScore: source.subscriberValueScore ?? inferSubscriberValueScore(source),
  };
}

const BASE_OSINT_SOURCE_CATALOG: BaseOsintSource[] = [
  {
    id: "acled",
    name: "ACLED",
    category: "conflict_tracker",
    description: "Armed Conflict Location and Event Data with global conflict event monitoring.",
    url: "https://acleddata.com/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["conflict-events", "dataset", "global"],
  },
  {
    id: "criticalthreats",
    name: "Critical Threats Project",
    category: "regional_analyst",
    description: "ISW/AEI project publishing conflict assessments and maps.",
    url: "https://www.criticalthreats.org/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["analysis", "maps", "security"],
  },
  {
    id: "isw",
    name: "Institute for the Study of War",
    category: "regional_analyst",
    description: "Daily war assessments and campaign updates.",
    url: "https://www.understandingwar.org/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["war-assessment", "daily-brief", "maps"],
  },
  {
    id: "bellingcat",
    name: "Bellingcat",
    category: "osint_collective",
    description: "Open-source investigations and geolocation-based reporting.",
    url: "https://www.bellingcat.com/",
    feedUrl: "https://www.bellingcat.com/feed/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["investigations", "geolocation", "forensics"],
  },
  {
    id: "airwars",
    name: "Airwars",
    category: "humanitarian",
    description: "Civilian harm monitoring and incident investigations in conflict zones.",
    url: "https://airwars.org/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["civilian-harm", "airstrikes", "investigations"],
  },
  {
    id: "forensic-architecture",
    name: "Forensic Architecture",
    category: "osint_collective",
    description: "Multimedia and spatial investigations for conflict events.",
    url: "https://forensic-architecture.org/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["forensics", "multimedia", "investigations"],
  },
  {
    id: "icg",
    name: "International Crisis Group",
    category: "regional_analyst",
    description: "Conflict analysis and early warning reports by region.",
    url: "https://www.crisisgroup.org/",
    feedUrl: "https://www.crisisgroup.org/rss.xml",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["policy", "analysis", "early-warning"],
  },
  {
    id: "reliefweb",
    name: "ReliefWeb",
    category: "humanitarian",
    description: "UN OCHA platform for humanitarian crisis and conflict situation reports.",
    url: "https://reliefweb.int/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["humanitarian", "sitreps", "alerts"],
  },
  {
    id: "gdelt",
    name: "GDELT Project",
    category: "conflict_tracker",
    description: "Global event and media monitoring dataset with near real-time updates.",
    url: "https://www.gdeltproject.org/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["events", "media-monitoring", "dataset"],
  },
  {
    id: "liveuamap",
    name: "LiveUAMap",
    category: "conflict_tracker",
    description: "Map-based conflict incident aggregation across regions.",
    url: "https://liveuamap.com/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["map", "incidents", "alerts"],
  },
  {
    id: "cfr-cpa",
    name: "CFR Global Conflict Tracker",
    category: "conflict_tracker",
    description: "Council on Foreign Relations conflict tracker and risk overviews.",
    url: "https://www.cfr.org/global-conflict-tracker",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["tracker", "risk", "policy"],
  },
  {
    id: "reuters-world",
    name: "Reuters World News",
    category: "newsroom",
    description: "International wire coverage for conflict and security developments.",
    url: "https://www.reuters.com/world/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["wire", "breaking", "global"],
  },
  {
    id: "ap-world",
    name: "AP World",
    category: "newsroom",
    description: "Associated Press global conflict and diplomatic reporting.",
    url: "https://apnews.com/world-news",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["wire", "world", "breaking"],
  },
  {
    id: "cnn-world",
    name: "CNN World",
    category: "newsroom",
    description: "High-cadence global conflict and security updates.",
    url: "https://www.cnn.com/world",
    feedUrl: "http://rss.cnn.com/rss/edition_world.rss",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["world", "breaking", "global"],
  },
  {
    id: "euronews-world",
    name: "Euronews",
    category: "newsroom",
    description: "European and global geopolitical coverage with continuous updates.",
    url: "https://www.euronews.com/news",
    feedUrl: "https://www.euronews.com/rss?level=theme&name=news",
    region: "europe",
    language: "en",
    reliability: "medium",
    tags: ["europe", "world", "breaking"],
  },
  {
    id: "bbc-world",
    name: "BBC World",
    category: "newsroom",
    description: "BBC international conflict and security coverage.",
    url: "https://www.bbc.com/news/world",
    feedUrl: "http://feeds.bbci.co.uk/news/world/rss.xml",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["world", "analysis", "breaking"],
  },
  {
    id: "aljazeera-world",
    name: "Al Jazeera",
    category: "newsroom",
    description: "Global conflict and regional breaking coverage.",
    url: "https://www.aljazeera.com/",
    feedUrl: "https://www.aljazeera.com/xml/rss/all.xml",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["world", "middle-east", "breaking"],
  },
  {
    id: "kyivindependent",
    name: "Kyiv Independent",
    category: "newsroom",
    description: "Ukraine-focused conflict and defense reporting.",
    url: "https://kyivindependent.com/",
    region: "europe",
    language: "en",
    reliability: "high",
    tags: ["ukraine", "defense", "regional"],
  },
  {
    id: "iiss",
    name: "IISS",
    category: "regional_analyst",
    description: "International Institute for Strategic Studies analysis.",
    url: "https://www.iiss.org/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["strategy", "defense", "analysis"],
  },
  {
    id: "jamestown",
    name: "Jamestown Foundation",
    category: "regional_analyst",
    description: "Regional security and conflict-focused analytical briefs.",
    url: "https://jamestown.org/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["security", "regional", "briefs"],
  },
  {
    id: "amna",
    name: "Armed Conflict and Location Monitor (ACLED regional outputs)",
    category: "conflict_tracker",
    description: "Regional conflict trend dashboards and short event summaries.",
    url: "https://acleddata.com/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["regional", "dashboard", "events"],
  },
  {
    id: "carnegie-middle-east",
    name: "Carnegie Middle East Center",
    category: "regional_analyst",
    description: "Middle East political-security analysis and commentary.",
    url: "https://carnegie-mec.org/",
    region: "middle-east",
    language: "en",
    reliability: "high",
    tags: ["middle-east", "analysis", "policy"],
  },
  {
    id: "africa-center",
    name: "Africa Center for Strategic Studies",
    category: "regional_analyst",
    description: "African security and conflict trend analysis.",
    url: "https://africacenter.org/",
    region: "africa",
    language: "en",
    reliability: "high",
    tags: ["africa", "security", "analysis"],
  },
  {
    id: "latinnews",
    name: "InSight Crime",
    category: "regional_analyst",
    description: "Latin America security, armed groups, and organized violence reporting.",
    url: "https://insightcrime.org/",
    feedUrl: "https://insightcrime.org/feed/",
    region: "latin-america",
    language: "en",
    reliability: "high",
    tags: ["latin-america", "security", "organized-violence"],
  },
  {
    id: "un-news",
    name: "UN News",
    category: "humanitarian",
    description: "United Nations newsroom covering conflicts, diplomacy, and humanitarian operations.",
    url: "https://news.un.org/en/",
    feedUrl: "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["un", "humanitarian", "diplomacy"],
  },
  {
    id: "nato-news",
    name: "NATO Newsroom",
    category: "regional_analyst",
    description: "Alliance statements, security updates, and operational posture announcements.",
    url: "https://www.nato.int/",
    region: "europe",
    language: "en",
    reliability: "high",
    tags: ["nato", "defense", "europe"],
  },
  {
    id: "guardian-world",
    name: "The Guardian World",
    category: "newsroom",
    description: "International affairs and conflict coverage with continuous updates.",
    url: "https://www.theguardian.com/world",
    feedUrl: "https://www.theguardian.com/world/rss",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["world", "breaking", "global"],
  },
  {
    id: "npr-world",
    name: "NPR World",
    category: "newsroom",
    description: "NPR reporting on global conflict, diplomacy, and security developments.",
    url: "https://www.npr.org/sections/world/",
    feedUrl: "https://feeds.npr.org/1004/rss.xml",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["radio", "world", "analysis"],
  },
  {
    id: "dw-world",
    name: "Deutsche Welle World",
    category: "newsroom",
    description: "German international broadcaster with global conflict and policy reporting.",
    url: "https://www.dw.com/en/top-stories/s-9097",
    feedUrl: "https://rss.dw.com/rdf/rss-en-world",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["world", "europe", "analysis"],
  },
  {
    id: "france24",
    name: "France 24",
    category: "newsroom",
    description: "Global newsroom with coverage of conflict theaters and foreign policy.",
    url: "https://www.france24.com/en/",
    feedUrl: "https://www.france24.com/en/rss",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["world", "breaking", "diplomacy"],
  },
  {
    id: "times-of-israel",
    name: "Times of Israel",
    category: "newsroom",
    description: "Middle East security and conflict reporting, including real-time developments.",
    url: "https://www.timesofisrael.com/",
    feedUrl: "https://www.timesofisrael.com/feed/",
    region: "middle-east",
    language: "en",
    reliability: "medium",
    tags: ["middle-east", "security", "regional"],
  },
  {
    id: "jerusalem-post",
    name: "Jerusalem Post",
    category: "newsroom",
    description: "Middle East geopolitics and defense reporting from an Israeli newsroom.",
    url: "https://www.jpost.com/",
    feedUrl: "https://www.jpost.com/rss/rssfeedsfrontpage.aspx",
    region: "middle-east",
    language: "en",
    reliability: "medium",
    tags: ["middle-east", "defense", "regional"],
  },
  {
    id: "nhk-world",
    name: "NHK World",
    category: "newsroom",
    description: "Japan-based international broadcaster covering East Asia and Indo-Pacific developments.",
    url: "https://www3.nhk.or.jp/nhkworld/",
    feedUrl: "https://www3.nhk.or.jp/rss/news/cat0.xml",
    region: "east_asia",
    language: "en",
    reliability: "high",
    tags: ["east-asia", "indo-pacific", "regional"],
  },
  {
    id: "anadolu-world",
    name: "Anadolu Agency",
    category: "newsroom",
    description: "Regional breaking coverage across Middle East, Europe, and global theaters.",
    url: "https://www.aa.com.tr/en",
    feedUrl: "https://www.aa.com.tr/en/rss/default?cat=world",
    region: "middle-east",
    language: "en",
    reliability: "medium",
    tags: ["middle-east", "wire", "breaking"],
  },
  {
    id: "elpais-english",
    name: "El País",
    category: "newsroom",
    description: "Spanish newsroom with global geopolitics and conflict coverage.",
    url: "https://elpais.com/",
    feedUrl: "https://elpais.com/rss/elpais/portada.xml",
    region: "europe",
    language: "es",
    reliability: "high",
    tags: ["europe", "analysis", "global"],
  },
  {
    id: "lemonde-international",
    name: "Le Monde International",
    category: "newsroom",
    description: "French newsroom international reporting in English with conflict focus.",
    url: "https://www.lemonde.fr/en/",
    feedUrl: "https://www.lemonde.fr/en/international/rss_full.xml",
    region: "europe",
    language: "en",
    reliability: "high",
    tags: ["europe", "international", "analysis"],
  },
  {
    id: "africanews",
    name: "Africanews",
    category: "newsroom",
    description: "Pan-African newsroom reporting conflict and political-security updates.",
    url: "https://www.africanews.com/",
    feedUrl: "https://www.africanews.com/feed/rss",
    region: "africa",
    language: "en",
    reliability: "high",
    tags: ["africa", "breaking", "regional"],
  },
  {
    id: "allafrica",
    name: "AllAfrica",
    category: "newsroom",
    description: "Africa-wide headline aggregation from local publishers and wires.",
    url: "https://allafrica.com/",
    feedUrl: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf",
    region: "africa",
    language: "en",
    reliability: "medium",
    tags: ["africa", "aggregation", "regional"],
  },
  {
    id: "defense-one",
    name: "Defense One",
    category: "regional_analyst",
    description: "US defense policy and military capability reporting.",
    url: "https://www.defenseone.com/",
    feedUrl: "https://www.defenseone.com/rss/all/",
    region: "us",
    language: "en",
    reliability: "high",
    tags: ["defense", "military", "policy"],
  },
  {
    id: "defence-blog",
    name: "Defence Blog",
    category: "osint_collective",
    description: "Military hardware and battlefield reporting with rapid updates.",
    url: "https://defence-blog.com/",
    feedUrl: "https://defence-blog.com/feed/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["military", "equipment", "defense"],
  },
  {
    id: "defense-news",
    name: "Defense News",
    category: "newsroom",
    description: "Global military operations and defense-industry reporting.",
    url: "https://www.defensenews.com/",
    feedUrl: "https://www.defensenews.com/arc/outboundfeeds/rss/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["defense", "military", "industry"],
  },
  {
    id: "breaking-defense",
    name: "Breaking Defense",
    category: "regional_analyst",
    description: "Defense policy, capability, and procurement analysis.",
    url: "https://breakingdefense.com/",
    feedUrl: "https://breakingdefense.com/feed/",
    region: "us",
    language: "en",
    reliability: "high",
    tags: ["defense", "policy", "analysis"],
  },
  {
    id: "hrw-news",
    name: "Human Rights Watch News",
    category: "humanitarian",
    description: "Conflict-related rights reporting, incidents, and humanitarian alerts.",
    url: "https://www.hrw.org/news",
    feedUrl: "https://www.hrw.org/rss/news",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["humanitarian", "rights", "conflict"],
  },
  {
    id: "uk-mod-news",
    name: "UK Ministry of Defence",
    category: "regional_analyst",
    description: "Official UK defence updates, operations, and posture statements.",
    url: "https://www.gov.uk/government/organisations/ministry-of-defence",
    feedUrl: "https://www.gov.uk/government/organisations/ministry-of-defence.atom",
    region: "europe",
    language: "en",
    reliability: "high",
    tags: ["uk", "defense", "official"],
  },
  {
    id: "uk-fcdo-news",
    name: "UK FCDO",
    category: "regional_analyst",
    description: "UK foreign policy and diplomatic updates on global crises.",
    url: "https://www.gov.uk/government/organisations/foreign-commonwealth-development-office",
    feedUrl: "https://www.gov.uk/government/organisations/foreign-commonwealth-development-office.atom",
    region: "europe",
    language: "en",
    reliability: "high",
    tags: ["uk", "diplomacy", "official"],
  },
  {
    id: "naval-news",
    name: "Naval News",
    category: "osint_collective",
    description: "Naval warfare, fleet deployments, and maritime defense analysis.",
    url: "https://www.navalnews.com/",
    feedUrl: "https://www.navalnews.com/feed/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["naval", "maritime", "defense"],
  },
  {
    id: "middle-east-eye",
    name: "Middle East Eye",
    category: "newsroom",
    description: "Middle East conflict reporting, diplomacy, and security coverage.",
    url: "https://www.middleeasteye.net/",
    feedUrl: "https://www.middleeasteye.net/rss.xml",
    region: "middle-east",
    language: "en",
    reliability: "medium",
    tags: ["middle-east", "conflict", "regional"],
  },
  {
    id: "al-monitor",
    name: "Al-Monitor",
    category: "newsroom",
    description: "Middle East policy and conflict intelligence from regional desks.",
    url: "https://www.al-monitor.com/",
    feedUrl: "https://www.al-monitor.com/rss",
    region: "middle-east",
    language: "en",
    reliability: "high",
    tags: ["middle-east", "policy", "analysis"],
  },
  {
    id: "scmp-world",
    name: "South China Morning Post World",
    category: "newsroom",
    description: "Asia-focused global security and geopolitical reporting.",
    url: "https://www.scmp.com/",
    feedUrl: "https://www.scmp.com/rss/91/feed",
    region: "east_asia",
    language: "en",
    reliability: "high",
    tags: ["east-asia", "geopolitics", "regional"],
  },
  {
    id: "diplomat",
    name: "The Diplomat",
    category: "regional_analyst",
    description: "Indo-Pacific strategy and defense analysis.",
    url: "https://thediplomat.com/",
    feedUrl: "https://thediplomat.com/feed/",
    region: "east_asia",
    language: "en",
    reliability: "high",
    tags: ["indo-pacific", "strategy", "analysis"],
  },
  {
    id: "straits-times-world",
    name: "The Straits Times World",
    category: "newsroom",
    description: "Asia-Pacific and global conflict reporting from Singapore.",
    url: "https://www.straitstimes.com/",
    feedUrl: "https://www.straitstimes.com/news/world/rss.xml",
    region: "east_asia",
    language: "en",
    reliability: "high",
    tags: ["asia-pacific", "world", "regional"],
  },
  {
    id: "times-of-india-world",
    name: "Times of India World",
    category: "newsroom",
    description: "South Asia and global geopolitical coverage.",
    url: "https://timesofindia.indiatimes.com/world",
    feedUrl: "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms",
    region: "south_asia",
    language: "en",
    reliability: "medium",
    tags: ["south-asia", "world", "regional"],
  },
  {
    id: "dawn-world",
    name: "Dawn",
    category: "newsroom",
    description: "Pakistan-focused and regional security reporting.",
    url: "https://www.dawn.com/",
    feedUrl: "https://www.dawn.com/feeds/home",
    region: "south_asia",
    language: "en",
    reliability: "medium",
    tags: ["south-asia", "regional", "security"],
  },
  {
    id: "geo-world",
    name: "Geo News",
    category: "newsroom",
    description: "South Asia breaking and regional conflict updates.",
    url: "https://www.geo.tv/",
    feedUrl: "https://www.geo.tv/rss/1/1",
    region: "south_asia",
    language: "en",
    reliability: "medium",
    tags: ["south-asia", "breaking", "regional"],
  },
  {
    id: "the-hindu-international",
    name: "The Hindu International",
    category: "newsroom",
    description: "International affairs and conflict reporting from India.",
    url: "https://www.thehindu.com/news/international/",
    feedUrl: "https://www.thehindu.com/news/international/feeder/default.rss",
    region: "south_asia",
    language: "en",
    reliability: "high",
    tags: ["south-asia", "international", "analysis"],
  },
  {
    id: "abc-au-world",
    name: "ABC Australia World",
    category: "newsroom",
    description: "Australia-based world and Indo-Pacific security coverage.",
    url: "https://www.abc.net.au/news/world/",
    feedUrl: "https://www.abc.net.au/news/feed/45910/rss.xml",
    region: "pacific",
    language: "en",
    reliability: "high",
    tags: ["pacific", "indo-pacific", "world"],
  },
  {
    id: "rnz-world",
    name: "Radio New Zealand World",
    category: "newsroom",
    description: "Pacific-focused international conflict and diplomacy reporting.",
    url: "https://www.rnz.co.nz/world",
    feedUrl: "https://www.rnz.co.nz/rss/world.xml",
    region: "pacific",
    language: "en",
    reliability: "high",
    tags: ["pacific", "world", "regional"],
  },
  {
    id: "lbci-world",
    name: "LBCI Lebanon",
    category: "newsroom",
    description: "Lebanon and Levant conflict/security updates in English.",
    url: "https://www.lbcgroup.tv/news/en",
    feedUrl: "https://www.lbcgroup.tv/rss/news/en",
    region: "middle-east",
    language: "en",
    reliability: "medium",
    tags: ["middle-east", "levant", "regional"],
  },
  {
    id: "mondoweiss",
    name: "Mondoweiss",
    category: "regional_analyst",
    description: "Focused analysis and reporting on Israel-Palestine conflict developments.",
    url: "https://mondoweiss.net/",
    feedUrl: "https://mondoweiss.net/feed/",
    region: "middle-east",
    language: "en",
    reliability: "medium",
    tags: ["middle-east", "analysis", "palestine"],
  },
  {
    id: "insider-paper",
    name: "Insider Paper",
    category: "newsroom",
    description: "Fast global breaking alerts with conflict and security focus.",
    url: "https://insiderpaper.com/",
    feedUrl: "https://insiderpaper.com/feed/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["breaking", "alerts", "global"],
  },
  {
    id: "war-on-the-rocks",
    name: "War on the Rocks",
    category: "regional_analyst",
    description: "Defense strategy and conflict analysis from military-policy experts.",
    url: "https://warontherocks.com/",
    feedUrl: "https://warontherocks.com/feed/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["strategy", "defense", "analysis"],
  },
  {
    id: "dw-africa",
    name: "Deutsche Welle Africa",
    category: "newsroom",
    description: "Africa-focused conflict and governance reporting.",
    url: "https://www.dw.com/en/africa/s-12756",
    feedUrl: "https://rss.dw.com/xml/rss-en-africa",
    region: "africa",
    language: "en",
    reliability: "high",
    tags: ["africa", "regional", "analysis"],
  },
  {
    id: "dw-asia",
    name: "Deutsche Welle Asia",
    category: "newsroom",
    description: "Asia regional reporting on conflict and security developments.",
    url: "https://www.dw.com/en/asia/s-12758",
    feedUrl: "https://rss.dw.com/xml/rss-en-asia",
    region: "east_asia",
    language: "en",
    reliability: "high",
    tags: ["east-asia", "regional", "analysis"],
  },
  {
    id: "oryx",
    name: "Oryx",
    category: "osint_collective",
    description: "Open-source equipment loss tracking in conflicts.",
    url: "https://www.oryxspioenkop.com/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["equipment-losses", "visual-verification", "war"],
  },
  {
    id: "gdacs-alerts",
    name: "GDACS Alerts",
    category: "conflict_tracker",
    description: "Global disaster alerting and event summaries for sudden-onset crises.",
    url: "https://www.gdacs.org/",
    feedUrl: "https://www.gdacs.org/xml/rss.xml",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["disaster", "alerts", "events"],
  },
  {
    id: "usgs-earthquakes",
    name: "USGS Earthquake Hazards",
    category: "conflict_tracker",
    description: "Near real-time global earthquake event reporting and machine-readable feeds.",
    url: "https://earthquake.usgs.gov/",
    feedUrl: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.atom",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["earthquake", "alerts", "dataset"],
  },
  {
    id: "emsc-quakes",
    name: "EMSC Earthquakes",
    category: "conflict_tracker",
    description: "European-Mediterranean Seismological Centre rapid earthquake alerts and updates.",
    url: "https://www.emsc-csem.org/",
    feedUrl: "https://www.emsc-csem.org/service/rss/rss.php?typ=emsc",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["earthquake", "alerts", "europe"],
  },
  {
    id: "nasa-firms",
    name: "NASA FIRMS",
    category: "conflict_tracker",
    description: "Fire and thermal anomaly monitoring useful for wildfire and strike-adjacent heat signatures.",
    url: "https://firms.modaps.eosdis.nasa.gov/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["fire", "satellite", "alerts"],
  },
  {
    id: "copernicus-ems",
    name: "Copernicus Emergency Management Service",
    category: "humanitarian",
    description: "European rapid mapping, emergency activation, and disaster response products.",
    url: "https://emergency.copernicus.eu/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["emergency", "mapping", "satellite"],
  },
  {
    id: "noaa-space-weather",
    name: "NOAA Space Weather",
    category: "conflict_tracker",
    description: "Official space weather alerts and solar activity bulletins relevant to comms and navigation disruptions.",
    url: "https://www.swpc.noaa.gov/",
    feedUrl: "https://www.swpc.noaa.gov/feeds/notifications.xml",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["space-weather", "alerts", "infrastructure"],
  },
  {
    id: "nasa-earth-observatory",
    name: "NASA Earth Observatory",
    category: "osint_collective",
    description: "Satellite imagery explainers and observation products for fires, floods, storms, and terrain shifts.",
    url: "https://earthobservatory.nasa.gov/",
    feedUrl: "https://earthobservatory.nasa.gov/feeds/image-of-the-day.rss",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["satellite", "imagery", "earth-observation"],
  },
  {
    id: "sentinel-hub",
    name: "Sentinel Hub Blog",
    category: "osint_collective",
    description: "EO and satellite-imagery workflows relevant to rapid visual verification.",
    url: "https://www.sentinel-hub.com/blog/",
    feedUrl: "https://www.sentinel-hub.com/blog/feed/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["satellite", "imagery", "geospatial"],
  },
  {
    id: "ifrc-emergency",
    name: "IFRC Emergency Appeals",
    category: "humanitarian",
    description: "Public disaster and humanitarian emergency reporting from the International Federation of Red Cross and Red Crescent Societies.",
    url: "https://www.ifrc.org/emergency-appeals",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["humanitarian", "disaster", "appeals"],
  },
  {
    id: "insecurity-insight",
    name: "Insecurity Insight",
    category: "humanitarian",
    description: "Monitoring violence affecting aid, health, education, and protection environments in crises.",
    url: "https://insecurityinsight.org/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["humanitarian", "crisis", "monitoring"],
  },
  {
    id: "opensky-network",
    name: "OpenSky Network",
    category: "conflict_tracker",
    description: "Open aircraft state and flight tracking data for rapid aviation monitoring.",
    url: "https://opensky-network.org/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["aviation", "ads-b", "tracking"],
  },
  {
    id: "adsbexchange",
    name: "ADS-B Exchange",
    category: "osint_collective",
    description: "Public aircraft tracking platform widely used for military flight OSINT.",
    url: "https://www.adsbexchange.com/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["aviation", "tracking", "military"],
  },
  {
    id: "flightradar24-blog",
    name: "Flightradar24 Blog",
    category: "newsroom",
    description: "Flight-tracking explainers and notable aviation event coverage.",
    url: "https://www.flightradar24.com/blog/",
    feedUrl: "https://www.flightradar24.com/blog/feed/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["aviation", "tracking", "blog"],
  },
  {
    id: "marine-traffic",
    name: "MarineTraffic",
    category: "conflict_tracker",
    description: "Public vessel tracking platform covering commercial and government maritime movement.",
    url: "https://www.marinetraffic.com/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["maritime", "ais", "tracking"],
  },
  {
    id: "gcaptain",
    name: "gCaptain",
    category: "newsroom",
    description: "Commercial shipping, naval incidents, and maritime security reporting.",
    url: "https://gcaptain.com/",
    feedUrl: "https://gcaptain.com/feed/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["maritime", "shipping", "security"],
  },
  {
    id: "usni-news",
    name: "USNI News",
    category: "newsroom",
    description: "Naval operations, fleet posture, and Indo-Pacific maritime reporting.",
    url: "https://news.usni.org/",
    feedUrl: "https://news.usni.org/feed",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["naval", "maritime", "defense"],
  },
  {
    id: "the-war-zone",
    name: "The War Zone",
    category: "newsroom",
    description: "Rapid military aviation, weapons, and defense reporting with strong open-source signal pickup.",
    url: "https://www.twz.com/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["aviation", "defense", "weapons"],
  },
  {
    id: "maritime-executive",
    name: "The Maritime Executive",
    category: "newsroom",
    description: "Global maritime operations, incidents, and shipping security coverage.",
    url: "https://maritime-executive.com/",
    feedUrl: "https://maritime-executive.com/rss/news",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["maritime", "shipping", "global"],
  },
  {
    id: "lloyds-list",
    name: "Lloyd's List",
    category: "newsroom",
    description: "Maritime trade, fleet risk, and shipping disruption reporting.",
    url: "https://lloydslist.com/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["maritime", "trade", "risk"],
  },
  {
    id: "us-centcom",
    name: "US CENTCOM News",
    category: "newsroom",
    description: "Official US Central Command operational statements and updates.",
    url: "https://www.centcom.mil/MEDIA/NEWS-ARTICLES/",
    region: "middle-east",
    language: "en",
    reliability: "high",
    tags: ["official", "military", "middle-east"],
  },
  {
    id: "cisa-alerts",
    name: "CISA Alerts",
    category: "regional_analyst",
    description: "Official US cyber alerts, advisories, and incident-focused security bulletins.",
    url: "https://www.cisa.gov/news-events/alerts",
    feedUrl: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
    region: "us",
    language: "en",
    reliability: "high",
    tags: ["cyber", "alerts", "official"],
  },
  {
    id: "cisa-kev",
    name: "CISA Known Exploited Vulnerabilities",
    category: "conflict_tracker",
    description: "Machine-readable catalog of vulnerabilities known to be exploited in the wild.",
    url: "https://www.cisa.gov/known-exploited-vulnerabilities-catalog",
    region: "us",
    language: "en",
    reliability: "high",
    tags: ["cyber", "vulnerabilities", "dataset"],
  },
  {
    id: "nvd-nist",
    name: "NIST National Vulnerability Database",
    category: "conflict_tracker",
    description: "Structured vulnerability feeds and enrichment for public CVE monitoring.",
    url: "https://nvd.nist.gov/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "cve", "dataset"],
  },
  {
    id: "cert-eu",
    name: "CERT-EU",
    category: "regional_analyst",
    description: "European Union cyber advisories, threat notes, and incident guidance.",
    url: "https://cert.europa.eu/",
    region: "europe",
    language: "en",
    reliability: "high",
    tags: ["cyber", "advisories", "europe"],
  },
  {
    id: "sans-isc",
    name: "SANS Internet Storm Center",
    category: "regional_analyst",
    description: "Operational internet threat diary and incident-driven security analysis.",
    url: "https://isc.sans.edu/",
    feedUrl: "https://isc.sans.edu/rssfeed_full.xml",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "incidents", "analysis"],
  },
  {
    id: "cisco-talos",
    name: "Cisco Talos",
    category: "regional_analyst",
    description: "Threat research, malware analysis, and incident tracking from Cisco Talos.",
    url: "https://blog.talosintelligence.com/",
    feedUrl: "https://blog.talosintelligence.com/feeds/posts/default",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "malware", "threat-intel"],
  },
  {
    id: "securelist",
    name: "Securelist",
    category: "regional_analyst",
    description: "Kaspersky research portal for malware, intrusion sets, and cyber operations.",
    url: "https://securelist.com/",
    feedUrl: "https://securelist.com/feed/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "malware", "research"],
  },
  {
    id: "mandiant-blog",
    name: "Mandiant Blog",
    category: "regional_analyst",
    description: "Incident response case studies, threat actor reporting, and cyber operations analysis.",
    url: "https://www.mandiant.com/resources/blog",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "incident-response", "threat-intel"],
  },
  {
    id: "crowdstrike-blog",
    name: "CrowdStrike Blog",
    category: "regional_analyst",
    description: "Threat hunting, actor tracking, and incident reporting from CrowdStrike.",
    url: "https://www.crowdstrike.com/blog/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "threat-intel", "actors"],
  },
  {
    id: "microsoft-security-blog",
    name: "Microsoft Security Blog",
    category: "regional_analyst",
    description: "Microsoft's public security, abuse, and threat research reporting.",
    url: "https://www.microsoft.com/en-us/security/blog/",
    feedUrl: "https://www.microsoft.com/en-us/security/blog/feed/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "research", "threat-intel"],
  },
  {
    id: "unit42",
    name: "Unit 42",
    category: "regional_analyst",
    description: "Palo Alto Unit 42 threat intelligence, malware, and incident response reporting.",
    url: "https://unit42.paloaltonetworks.com/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "malware", "research"],
  },
  {
    id: "google-threat-intelligence",
    name: "Google Threat Intelligence",
    category: "regional_analyst",
    description: "Public threat research and actor reporting from Google security teams.",
    url: "https://cloud.google.com/blog/topics/threat-intelligence",
    feedUrl: "https://cloud.google.com/feeds/threat-intelligence.xml",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "threat-intel", "research"],
  },
  {
    id: "sentinelone-labs",
    name: "SentinelLABS",
    category: "regional_analyst",
    description: "Malware, intrusion, and threat actor research from SentinelOne.",
    url: "https://www.sentinelone.com/labs/",
    feedUrl: "https://www.sentinelone.com/labs/feed/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "malware", "research"],
  },
  {
    id: "trendmicro-research",
    name: "Trend Micro Research",
    category: "regional_analyst",
    description: "Threat research, campaigns, and exploit reporting from Trend Micro.",
    url: "https://www.trendmicro.com/en_us/research.html",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "research", "campaigns"],
  },
  {
    id: "recorded-future-blog",
    name: "Recorded Future Blog",
    category: "regional_analyst",
    description: "Threat intelligence reporting and public cyber risk analysis.",
    url: "https://www.recordedfuture.com/blog",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["cyber", "risk", "analysis"],
  },
  {
    id: "bleepingcomputer",
    name: "BleepingComputer",
    category: "newsroom",
    description: "High-cadence cyber incident, exploit, and vulnerability reporting.",
    url: "https://www.bleepingcomputer.com/",
    feedUrl: "https://www.bleepingcomputer.com/feed/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "breaking", "incidents"],
  },
  {
    id: "securityweek",
    name: "SecurityWeek",
    category: "newsroom",
    description: "Enterprise and public cyber incident, policy, and vulnerability reporting.",
    url: "https://www.securityweek.com/",
    feedUrl: "https://feeds.feedburner.com/securityweek",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "incidents", "enterprise"],
  },
  {
    id: "the-hacker-news",
    name: "The Hacker News",
    category: "newsroom",
    description: "Fast-moving cybersecurity reporting with exploit and threat actor coverage.",
    url: "https://thehackernews.com/",
    feedUrl: "https://feeds.feedburner.com/TheHackersNews",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["cyber", "breaking", "vulnerabilities"],
  },
  {
    id: "dark-reading",
    name: "Dark Reading",
    category: "newsroom",
    description: "Security operations, vulnerability, and cyber policy reporting.",
    url: "https://www.darkreading.com/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "security-ops", "enterprise"],
  },
  {
    id: "theregister-security",
    name: "The Register Security",
    category: "newsroom",
    description: "Cybersecurity reporting with strong incident and infrastructure focus.",
    url: "https://www.theregister.com/security/",
    feedUrl: "https://www.theregister.com/security/headlines.atom",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["cyber", "incidents", "infrastructure"],
  },
  {
    id: "reddit-worldnews",
    name: "Reddit World News",
    category: "osint_collective",
    description: "Public world-news discussion stream useful for burst detection and source discovery.",
    url: "https://www.reddit.com/r/worldnews/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["social", "reddit", "burst-detection"],
  },
  {
    id: "reddit-geopolitics",
    name: "Reddit Geopolitics",
    category: "osint_collective",
    description: "Public geopolitics discussion and source aggregation.",
    url: "https://www.reddit.com/r/geopolitics/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["social", "reddit", "geopolitics"],
  },
  {
    id: "reddit-cybersecurity",
    name: "Reddit Cybersecurity",
    category: "osint_collective",
    description: "Public cyber discussion stream for vulnerability, incident, and tooling chatter.",
    url: "https://www.reddit.com/r/cybersecurity/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["social", "reddit", "cyber"],
  },
  {
    id: "bluesky-osint",
    name: "Bluesky OSINT Lists",
    category: "osint_collective",
    description: "Public Bluesky OSINT and researcher account monitoring for rapid source discovery.",
    url: "https://bsky.app/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["social", "bluesky", "osint"],
  },
  {
    id: "mastodon-infosec",
    name: "Mastodon Infosec",
    category: "osint_collective",
    description: "Public infosec and incident-response accounts on the fediverse.",
    url: "https://infosec.exchange/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["social", "mastodon", "cyber"],
  },
  {
    id: "youtube-visual-investigations",
    name: "YouTube Visual Investigations",
    category: "osint_collective",
    description: "Public long-form visual investigations, livestream archives, and geolocation explainers.",
    url: "https://www.youtube.com/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["video", "social", "visual-investigations"],
  },
  {
    id: "telegram-public-watch",
    name: "Telegram Public Watchlists",
    category: "osint_collective",
    description: "Public Telegram discovery layer for monitored channels outside the core conflict set.",
    url: "https://telegram.org/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["telegram", "discovery", "social"],
  },
  {
    id: "x-public-monitor",
    name: "X Public Monitor",
    category: "osint_collective",
    description: "Public monitored account surface for high-velocity OSINT, government, and analyst chatter.",
    url: "https://x.com/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["social", "x", "breaking"],
  },
  {
    id: "watcher-guru",
    name: "Watcher.Guru",
    category: "newsroom",
    description: "Fast public alerts useful for market, sanctions, and geopolitical financial signal pickup.",
    url: "https://watcher.guru/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["alerts", "finance", "breaking"],
  },
  {
    id: "intel-crab",
    name: "IntelCrab",
    category: "osint_collective",
    description: "Independent public OSINT investigations focused on conflict and military verification.",
    url: "https://intelcrab.com/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["osint", "verification", "investigations"],
  },
];

const EXPANDED_OSINT_SOURCE_CATALOG: BaseOsintSource[] = [
  {
    id: "gdacs-alerts",
    name: "GDACS Alerts",
    category: "conflict_tracker",
    description: "Global disaster alert coordination feeds for earthquakes, floods, cyclones, and crisis events.",
    url: "https://www.gdacs.org/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["alerts", "dataset", "global", "disaster", "api", "official"],
  },
  {
    id: "usgs-earthquakes",
    name: "USGS Earthquake Hazards",
    category: "conflict_tracker",
    description: "Near real-time earthquake feeds and event metadata from USGS.",
    url: "https://earthquake.usgs.gov/earthquakes/feed/",
    feedUrl: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.atom",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["alerts", "dataset", "global", "earthquake", "api", "official"],
  },
  {
    id: "emsc-quakes",
    name: "EMSC Earthquakes",
    category: "conflict_tracker",
    description: "European-Mediterranean Seismological Centre live earthquake event feed.",
    url: "https://www.emsc-csem.org/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["alerts", "dataset", "earthquake", "global", "api"],
  },
  {
    id: "nasa-firms",
    name: "NASA FIRMS",
    category: "conflict_tracker",
    description: "Fire and thermal anomaly monitoring useful for wildfire, strike, and burn-area intelligence.",
    url: "https://firms.modaps.eosdis.nasa.gov/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["dataset", "satellite", "image", "alerts", "global", "api"],
  },
  {
    id: "copernicus-ems",
    name: "Copernicus Emergency Management",
    category: "humanitarian",
    description: "Emergency mapping and disaster monitoring products from Copernicus EMS.",
    url: "https://emergency.copernicus.eu/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["map", "satellite", "document", "humanitarian", "official"],
  },
  {
    id: "noaa-space-weather",
    name: "NOAA Space Weather",
    category: "conflict_tracker",
    description: "Space weather alerts useful for communications, GPS, and disruption monitoring.",
    url: "https://www.swpc.noaa.gov/",
    feedUrl: "https://www.swpc.noaa.gov/products/alerts-watches-and-warnings",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["alerts", "official", "space-weather", "global"],
  },
  {
    id: "ifrc-emergency",
    name: "IFRC Emergency Appeals",
    category: "humanitarian",
    description: "International Federation of Red Cross emergency response and crisis updates.",
    url: "https://www.ifrc.org/emergencies",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["humanitarian", "alerts", "global", "official"],
  },
  {
    id: "insecurity-insight",
    name: "Insecurity Insight",
    category: "humanitarian",
    description: "Attack tracking and humanitarian security monitoring for health care, aid, and education.",
    url: "https://insecurityinsight.org/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["humanitarian", "conflict-events", "analysis", "global"],
  },
  {
    id: "opensky-network",
    name: "OpenSky Network",
    category: "conflict_tracker",
    description: "Public air traffic data and state vectors for aviation intelligence.",
    url: "https://opensky-network.org/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["ads-b", "aviation", "dataset", "api", "global"],
  },
  {
    id: "adsbexchange",
    name: "ADS-B Exchange",
    category: "osint_collective",
    description: "Public aircraft tracking ecosystem widely used for OSINT aviation monitoring.",
    url: "https://www.adsbexchange.com/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["ads-b", "aviation", "tracking", "global"],
  },
  {
    id: "flightradar24-blog",
    name: "Flightradar24 Blog",
    category: "newsroom",
    description: "Aviation event analysis and unusual flight activity reporting.",
    url: "https://www.flightradar24.com/blog/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["aviation", "analysis", "global", "tracking"],
  },
  {
    id: "marine-traffic",
    name: "MarineTraffic",
    category: "osint_collective",
    description: "Vessel tracking reference platform for maritime intelligence and AIS monitoring.",
    url: "https://www.marinetraffic.com/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["ais", "maritime", "tracking", "global"],
  },
  {
    id: "gcaptain",
    name: "gCaptain",
    category: "newsroom",
    description: "Maritime incident reporting and shipping/security updates.",
    url: "https://gcaptain.com/",
    feedUrl: "https://gcaptain.com/feed/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["maritime", "shipping", "breaking", "global"],
  },
  {
    id: "usni-news",
    name: "USNI News",
    category: "regional_analyst",
    description: "Naval, maritime, and strategic force reporting.",
    url: "https://news.usni.org/",
    feedUrl: "https://news.usni.org/feed",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["naval", "maritime", "analysis", "global"],
  },
  {
    id: "the-war-zone",
    name: "The War Zone",
    category: "newsroom",
    description: "Fast-moving defense, aviation, and strategic systems coverage.",
    url: "https://www.twz.com/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["defense", "aviation", "analysis", "strategic"],
  },
  {
    id: "maritime-executive",
    name: "The Maritime Executive",
    category: "newsroom",
    description: "Commercial and security-focused maritime reporting.",
    url: "https://maritime-executive.com/",
    feedUrl: "https://maritime-executive.com/rss/news",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["maritime", "shipping", "analysis", "global"],
  },
  {
    id: "lloyds-list",
    name: "Lloyd's List",
    category: "newsroom",
    description: "Shipping and maritime trade intelligence with operational relevance.",
    url: "https://lloydslist.maritimeintelligence.informa.com/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["maritime", "shipping", "analysis", "global"],
  },
  {
    id: "us-centcom",
    name: "US CENTCOM News",
    category: "newsroom",
    description: "Operational press releases and military statements from CENTCOM.",
    url: "https://www.centcom.mil/MEDIA/PRESS-RELEASES/",
    region: "middle-east",
    language: "en",
    reliability: "high",
    tags: ["official", "military", "middle-east", "press-releases"],
  },
  {
    id: "nasa-earth-observatory",
    name: "NASA Earth Observatory",
    category: "osint_collective",
    description: "Satellite and remote sensing imagery for natural hazards and environmental monitoring.",
    url: "https://earthobservatory.nasa.gov/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["satellite", "image", "global", "analysis"],
  },
  {
    id: "sentinel-hub",
    name: "Sentinel Hub Blog",
    category: "osint_collective",
    description: "Earth observation and Sentinel imagery workflows relevant to geospatial OSINT.",
    url: "https://www.sentinel-hub.com/blog/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["satellite", "image", "map", "analysis"],
  },
  {
    id: "cisa-alerts",
    name: "CISA Alerts",
    category: "regional_analyst",
    description: "Cybersecurity advisories and incident alerts from CISA.",
    url: "https://www.cisa.gov/news-events/cybersecurity-advisories",
    region: "us",
    language: "en",
    reliability: "high",
    tags: ["cyber", "alerts", "official", "advisory", "document"],
  },
  {
    id: "cisa-kev",
    name: "CISA Known Exploited Vulnerabilities",
    category: "conflict_tracker",
    description: "Machine-readable catalog of known exploited vulnerabilities.",
    url: "https://www.cisa.gov/known-exploited-vulnerabilities-catalog",
    region: "us",
    language: "en",
    reliability: "high",
    tags: ["cyber", "dataset", "api", "official", "vulnerabilities"],
  },
  {
    id: "nvd-nist",
    name: "NVD NIST",
    category: "conflict_tracker",
    description: "National Vulnerability Database feeds and CVE records.",
    url: "https://nvd.nist.gov/",
    region: "us",
    language: "en",
    reliability: "high",
    tags: ["cyber", "dataset", "api", "official", "vulnerabilities"],
  },
  {
    id: "cert-eu",
    name: "CERT-EU",
    category: "regional_analyst",
    description: "European cyber advisories and incident-focused publications.",
    url: "https://cert.europa.eu/",
    region: "europe",
    language: "en",
    reliability: "high",
    tags: ["cyber", "advisory", "official", "document", "europe"],
  },
  {
    id: "sans-isc",
    name: "SANS Internet Storm Center",
    category: "regional_analyst",
    description: "Daily cyber diary and operational threat observations.",
    url: "https://isc.sans.edu/",
    feedUrl: "https://isc.sans.edu/rssfeed.xml",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "analysis", "alerts", "global"],
  },
  {
    id: "cisco-talos",
    name: "Cisco Talos",
    category: "regional_analyst",
    description: "Threat research and vulnerability analysis from Cisco Talos.",
    url: "https://blog.talosintelligence.com/",
    feedUrl: "https://blog.talosintelligence.com/feeds/posts/default",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "analysis", "malware", "research"],
  },
  {
    id: "securelist",
    name: "Securelist",
    category: "regional_analyst",
    description: "Kaspersky research portal for malware and threat intelligence.",
    url: "https://securelist.com/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "analysis", "malware", "research"],
  },
  {
    id: "mandiant-blog",
    name: "Mandiant Blog",
    category: "regional_analyst",
    description: "Incident response and threat actor reporting.",
    url: "https://www.mandiant.com/resources/blog",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "incident-response", "analysis", "research"],
  },
  {
    id: "crowdstrike-blog",
    name: "CrowdStrike Blog",
    category: "regional_analyst",
    description: "Threat intelligence and incident reporting from CrowdStrike.",
    url: "https://www.crowdstrike.com/blog/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "incident-response", "analysis", "research"],
  },
  {
    id: "microsoft-security-blog",
    name: "Microsoft Security Blog",
    category: "regional_analyst",
    description: "Security research and threat reporting from Microsoft.",
    url: "https://www.microsoft.com/en-us/security/blog/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "analysis", "research", "official"],
  },
  {
    id: "unit42",
    name: "Unit 42",
    category: "regional_analyst",
    description: "Threat actor, malware, and vulnerability reporting from Unit 42.",
    url: "https://unit42.paloaltonetworks.com/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "analysis", "malware", "research"],
  },
  {
    id: "google-threat-intelligence",
    name: "Google Threat Intelligence",
    category: "regional_analyst",
    description: "Threat analysis, incident reporting, and strategic cyber intelligence from Google.",
    url: "https://cloud.google.com/blog/topics/threat-intelligence",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "analysis", "research", "official"],
  },
  {
    id: "sentinelone-labs",
    name: "SentinelOne Labs",
    category: "regional_analyst",
    description: "Malware, threat actor, and detection engineering research.",
    url: "https://www.sentinelone.com/labs/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "analysis", "malware", "research"],
  },
  {
    id: "trendmicro-research",
    name: "Trend Micro Research",
    category: "regional_analyst",
    description: "Threat research, campaigns, and vulnerability tracking.",
    url: "https://www.trendmicro.com/en_us/research.html",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "analysis", "malware", "research"],
  },
  {
    id: "recorded-future-blog",
    name: "Recorded Future",
    category: "regional_analyst",
    description: "Threat research and operational cyber intelligence reporting.",
    url: "https://www.recordedfuture.com/blog",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "analysis", "research", "intelligence"],
  },
  {
    id: "bleepingcomputer",
    name: "BleepingComputer",
    category: "newsroom",
    description: "High-tempo cyber incident and vulnerability reporting.",
    url: "https://www.bleepingcomputer.com/",
    feedUrl: "https://www.bleepingcomputer.com/feed/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "breaking", "newsroom", "global"],
  },
  {
    id: "securityweek",
    name: "SecurityWeek",
    category: "newsroom",
    description: "Enterprise and nation-state cyber security reporting.",
    url: "https://www.securityweek.com/",
    feedUrl: "https://feeds.feedburner.com/securityweek",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "breaking", "newsroom", "global"],
  },
  {
    id: "the-hacker-news",
    name: "The Hacker News",
    category: "newsroom",
    description: "High-tempo cyber news and exploit reporting.",
    url: "https://thehackernews.com/",
    feedUrl: "https://feeds.feedburner.com/TheHackersNews",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["cyber", "breaking", "newsroom", "global"],
  },
  {
    id: "dark-reading",
    name: "Dark Reading",
    category: "newsroom",
    description: "Cybersecurity news, incidents, and strategic enterprise coverage.",
    url: "https://www.darkreading.com/",
    region: "global",
    language: "en",
    reliability: "high",
    tags: ["cyber", "newsroom", "analysis", "global"],
  },
  {
    id: "theregister-security",
    name: "The Register Security",
    category: "newsroom",
    description: "Security and infrastructure reporting with high operational tempo.",
    url: "https://www.theregister.com/security/",
    feedUrl: "https://www.theregister.com/security/headlines.atom",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["cyber", "newsroom", "global", "breaking"],
  },
  {
    id: "reddit-worldnews",
    name: "Reddit r/worldnews",
    category: "newsroom",
    description: "Public social signal stream for global breaking events and amplification monitoring.",
    url: "https://www.reddit.com/r/worldnews/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["social", "reddit", "breaking", "global"],
  },
  {
    id: "reddit-geopolitics",
    name: "Reddit r/geopolitics",
    category: "regional_analyst",
    description: "Public geopolitical discussion and source discovery surface.",
    url: "https://www.reddit.com/r/geopolitics/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["social", "reddit", "analysis", "global"],
  },
  {
    id: "reddit-cybersecurity",
    name: "Reddit r/cybersecurity",
    category: "regional_analyst",
    description: "Public cyber incident and source-discovery surface.",
    url: "https://www.reddit.com/r/cybersecurity/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["social", "reddit", "cyber", "global"],
  },
  {
    id: "bluesky-osint",
    name: "Bluesky OSINT Monitor",
    category: "osint_collective",
    description: "Public Bluesky account monitoring for OSINT and breaking-event source discovery.",
    url: "https://bsky.app/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["social", "bluesky", "osint", "global"],
  },
  {
    id: "mastodon-infosec",
    name: "Mastodon Infosec Monitor",
    category: "osint_collective",
    description: "Public fediverse/infosec monitoring for cyber and incident chatter.",
    url: "https://mastodon.social/tags/infosec",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["social", "mastodon", "cyber", "global"],
  },
  {
    id: "youtube-visual-investigations",
    name: "YouTube Visual Investigations",
    category: "osint_collective",
    description: "Public video-rich source discovery for visual investigations and analyst channels.",
    url: "https://www.youtube.com/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["social", "youtube", "video", "osint", "global"],
  },
  {
    id: "telegram-public-watch",
    name: "Telegram Public Watch",
    category: "osint_collective",
    description: "Public Telegram source discovery and monitoring index for conflict and OSINT accounts.",
    url: "https://t.me/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["telegram", "social", "osint", "global"],
  },
  {
    id: "x-public-monitor",
    name: "X Public Monitor",
    category: "osint_collective",
    description: "Public high-tempo account monitoring across security, conflict, and infrastructure reporters.",
    url: "https://x.com/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["social", "x-monitor", "breaking", "global"],
  },
  {
    id: "watcher-guru",
    name: "Watcher.Guru",
    category: "newsroom",
    description: "High-tempo alerts useful for sanctions, market, and geopolitical narrative monitoring.",
    url: "https://watcher.guru/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["alerts", "breaking", "global", "social"],
  },
  {
    id: "intel-crab",
    name: "Intel Crab",
    category: "osint_collective",
    description: "Public OSINT source-discovery surface for conflict and strategic monitoring.",
    url: "https://intelcrab.com/",
    region: "global",
    language: "en",
    reliability: "medium",
    tags: ["osint", "analysis", "global", "social"],
  },
];

export const OSINT_SOURCE_CATALOG: OsintSource[] = [...BASE_OSINT_SOURCE_CATALOG, ...EXPANDED_OSINT_SOURCE_CATALOG].map(buildSource);
